version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers@sha256:1581875b98a4494eb1fc158714e20f5c65a22711e75c44b6d0737bcbb970205d
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: dist
