version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers@sha256:a29b2d863489a7064def90d01aa51980cfa1c2fe4e95b8d036e8590d8095086f
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: dist
